---
# data is stored in a variable whose name is the CSV file name without the extension
- include_csv:
    src: "{{serverList}}"
    outname: "my_serverList"

- include_csv:
    src: "{{appMapping}}"
    outname: "my_appMapping"

# es_serverList is the name of the csv.
# For compatibility of old versions, match is changed to match
- name: "Set Serverlist CSV variables"
  set_fact:
    cluster_master_grp: "{{ my_serverList | selectattr('hostGroup','match','^cluster_master$') | map(attribute='hostname') | list }}"
    dep_server_grp:     "{{ my_serverList | selectattr('hostGroup','match','^dep_server$') | map(attribute='hostname') | list }}"
    ind_slave_grp:      "{{ my_serverList | selectattr('hostGroup','match','^ind_slave$') | map(attribute='hostname') | list }}"
    license_master_grp: "{{ my_serverList | selectattr('hostGroup','match','^license_master$') | map(attribute='hostname') | list }}"
    shc_member_grp:     "{{ my_serverList | selectattr('hostGroup','match','^shc_member$') | map(attribute='hostname') | list }}"

- name: "Set Serverlist Concatenated variables"
  set_fact:
    distributedSearch_uri:  '{% set comma = joiner(",") -%} {% for host in shc_member_grp %}{{comma()}}{{protocol}}://{{host}}:{{mgmtPort}}{% endfor %}'
    distributedIndexer_uri: '{% set comma = joiner(",") -%} {% for host in ind_slave_grp %}{{comma()}}{{protocol}}://{{host}}:{{mgmtPort}}{% endfor %}'
    dep_server_uri:  '{% set comma = joiner(",") -%} {% for host in dep_server_grp %}{{comma()}}{{protocol}}://{{host}}:{{mgmtPort}}{% endfor %}'
    license_master_uri:  '{% set comma = joiner(",") -%} {% for host in license_master_grp %}{{comma()}}{{protocol}}://{{host}}:{{mgmtPort}}{% endfor %}'
    indexers_fwd_uri: '{% set comma = joiner(",") -%} {% for host in ind_slave_grp %}{{comma()}}{{host}}:{{fwdPort}}{% endfor %}'
