---
# data is stored in a variable whose name is the CSV file name without the extension
- include_csv:
    src: "{{serverList}}"
    outname: "my_serverList"

- include_csv:
    src: "{{appMapping}}"
    outname: "my_appMapping"

# sta_serverList is the name of the csv.
# For compatibility of old versions, match is changed to match

- name: "Set Serverlist CSV variables"
  set_fact:
    standalone_server: "{{ my_serverList | selectattr('hostGroup','match','^standalone$') | map(attribute='hostname') | list }}"
